name:                mealie-importer-haskell
version:             0.1.0.0
github:              "m472/mealie-importer"
license:             BSD-3-Clause
author:              "Mathias Graf"
maintainer:          "mathias.n.graf@gmail.com"
copyright:           "2024 Mathias Graf"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/m472/mealie-importer#readme>

dependencies:
- base >= 4.7 && < 5
- http-client
- http-client-tls
- bytestring
- network-uri
- scalpel
- utf8-string
- aeson
- split
- tagsoup
- extra
- mtl
- optparse-applicative
- filepath
- pureMD5
- containers
- time
- text
- servant
- servant-client
- transformers-either

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  mealie-importer-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mealie-importer-haskell

tests:
  mealie-importer-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mealie-importer-haskell
